/**
 * Comparison-shopping feed proxy — GET /s/{tenantSlug}/feeds/{provider}.xml
 * (per `29-integrations.md`). Gives the merchant a clean storefront URL to
 * register in Heureka / Zboží.cz / Glami; the XML is generated by the API.
 * Cached for an hour (the engines crawl periodically, not in real time).
 */

const API_VERSION = '2026-05-20';
const API_BASE = process.env.SHOPIO_API_URL ?? 'http://localhost:4040';

const PROVIDERS = new Set(['heureka', 'zbozi', 'glami']);

interface Ctx {
  params: Promise<{ tenantSlug: string; file: string }>;
}

export const revalidate = 3600;

export async function GET(_req: Request, ctx: Ctx): Promise<Response> {
  const { tenantSlug, file } = await ctx.params;
  const provider = file.replace(/\.xml$/, '');
  if (!PROVIDERS.has(provider)) return new Response('Not found', { status: 404 });

  const res = await fetch(
    `${API_BASE}/api/${API_VERSION}/storefront/${tenantSlug}/feeds/${provider}.xml`,
    { next: { revalidate: 3600 } },
  );
  if (!res.ok) return new Response('Not found', { status: res.status });

  const xml = await res.text();
  return new Response(xml, {
    headers: {
      'content-type': 'application/xml; charset=utf-8',
      'cache-control': 'public, max-age=3600',
    },
  });
}
