/**
 * Permission catalog. Per `36-personas-rbac.md §4`.
 *
 * Format: PERM-{RESOURCE}-{ACTION}
 * ~180 permissions total at MVP. Skeleton below — expand per domain implementation.
 */

export const PERMISSIONS = {
  // Catalog (per `06`)
  PRODUCT_VIEW: 'PERM-PRODUCT-VIEW',
  PRODUCT_CREATE: 'PERM-PRODUCT-CREATE',
  PRODUCT_EDIT: 'PERM-PRODUCT-EDIT',
  PRODUCT_DELETE: 'PERM-PRODUCT-DELETE',
  PRODUCT_PUBLISH: 'PERM-PRODUCT-PUBLISH',

  // Orders (per `12`, `16`)
  ORDER_VIEW: 'PERM-ORDER-VIEW',
  ORDER_VIEW_FULL_PII: 'PERM-ORDER-VIEW-FULL-PII',
  ORDER_EDIT: 'PERM-ORDER-EDIT',
  ORDER_CANCEL: 'PERM-ORDER-CANCEL',
  ORDER_REFUND: 'PERM-ORDER-REFUND',
  ORDER_REFUND_HIGH_VALUE: 'PERM-ORDER-REFUND-HIGH-VALUE',
  ORDER_FULFILL: 'PERM-ORDER-FULFILL',

  // Customers (per `18`)
  CUSTOMER_VIEW: 'PERM-CUSTOMER-VIEW',
  CUSTOMER_VIEW_FULL_PII: 'PERM-CUSTOMER-VIEW-FULL-PII',
  CUSTOMER_EDIT: 'PERM-CUSTOMER-EDIT',
  CUSTOMER_DELETE: 'PERM-CUSTOMER-DELETE',

  // Admin (per `27`)
  ADMIN_ACCESS: 'PERM-ADMIN-ACCESS',
  ADMIN_FULL: 'PERM-ADMIN-FULL',
  ADMIN_TEAM_MANAGE: 'PERM-ADMIN-TEAM-MANAGE',

  // Security (per `30`)
  SECURITY_VIEW: 'PERM-SECURITY-VIEW',
  SECURITY_MANAGE: 'PERM-SECURITY-MANAGE',
  AUDIT_LOG_VIEW: 'PERM-AUDIT-LOG-VIEW',

  // Platform-only (per `36`)
  PLATFORM_LOGIN: 'PERM-PLATFORM-LOGIN',
  PLATFORM_PRODUCTION_ACCESS: 'PERM-PLATFORM-PRODUCTION-ACCESS',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** All permission codes as readonly array. */
export const ALL_PERMISSION_CODES = Object.values(PERMISSIONS) as readonly PermissionCode[];
